name: Angular CI/CD

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches: ["main"]

jobs:
  # The "build" job
  build:
    runs-on: ubuntu-latest # Use a fresh virtual machine running Ubuntu

    steps:
      # 1. Check out your repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm" # This will cache node_modules for faster subsequent runs

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci # 'ci' is faster and safer for automated environments than 'install'

      # 4. Run linter
      - name: Lint code
        run: npm run lint

      # 5. Run unit tests
      - name: Run unit tests
        run: npm test -- --no-watch --browsers=ChromeHeadless

      # 6. Build the application for production
      - name: Build application
        run: ng build --configuration production --base-href /ci-cd-practice/

        # Important: --base-href is needed for GitHub Pages deployment!
      # 7. Upload the build artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder # A name for the artifact
          path: dist/ci-cd-practice/browser/ # The folder to upload

  deploy:
      needs: build
      runs-on: ubuntu-latest

      permissions:
        pages: write
        id-token: write

      steps:
        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: dist-folder

        - name: Deploy to Github Pages
          uses: actions/deploy-page@v4
